apiVersion: v1
kind: Pod
metadata:
  name: aws-efs-nginx
spec:
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: nginx-pvc-claim
  containers:
    - name: nginx-aws-efs
      image: nginx
      ports:
        - containerPort: 80
          name: "nginx"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nginx-vol