apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv
  labels:
    type: local
spec:
  storageClassName: aws-ebs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/aws-ebs"