apiVersion: v1
kind: Pod
metadata:
  name: devops-cm-env
spec:
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: devops-cm
  restartPolicy: Never