apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  labels:
    type: local
spec:
  storageClassName: aws-efs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/efs-data"